### ISSUE TITLE
settings.json error

### ISSUE THREAD

**Issue by vkuzmin-uber** [sectioneight/dotfiles#4]
VSCode version:
1.17.1
1e9d36539b0ae51ac09b9d4673ebea4e447e5353

Settings in file:
sectioneight/dotfiles/blob/master/library/VSCode/User/settings.json

Line:
    "files.exclude": {
        "out/**.js": true,

causes a problem in "Find in Files":

"Error parsing glob
'Users/vkuzmin/gocode/project..'
invalid use of **; must be one path component.

**Comment by sectioneight** [comment]
Hmm, I haven't use the latest VSCode in a while. However, it looks like you're trying to use `**` properly. The error message is actually pretty helpful -- it says that it must be part of the //path// component, but here you're trying to use it as part of the //file// component. Have you tried:

```
"out/*.js": true
```

?

**Comment by vkuzmin-uber** [comment]
Just realized that I have never replied. yes, I fixed mask. I copy-pasted from somewhere with error inside. I was confused that ** still valid mask in some cases:

    "files.exclude": {
        "out/*.js": true,
        "**/.tmp": true,

Anyway, it works!
