### ISSUE TITLE
Proposal: add popular custom printf-like names to "go vet"

### ISSUE THREAD

**Issue by vkuzmin-uber** [sectioneight/dotfiles#5]
https://github.com/sectioneight/dotfiles/blob/6de0efceaee41a4f5ec51f9e9f362a0f1d5325e0/library/VSCode/User/settings.json#L39

I started to use extra setting that allows "go vet" to catch errors in printf-like functions:

    "go.vetFlags": [
        "-printfuncs=wrapf,statusf,warnf,infof,debugf,noerrorf,equalf,newexiterrorf,containsf,truef,falsef,equalf,emptyf,failf"
    ],

If you are interested in details, I wrote a short article: https://kuzminva.wordpress.com/2017/11/07/go-vet-printf-family-check/

**Comment by sectioneight** [comment]
Thanks!
